language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - build-tools-26.0.1
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - ".+"
script:
- "./gradlew clean assembleDebug"
notifications:
  email: false
  slack:
    secure: YbgzFLTx2AHh0PtOGEQykSaKVvo5Fh/X/dkQUkxn1BmVfdAfnEbJmIw9EJw2IpzbceXGWrFFM+ho3Or28MuD7GegNHEcC1QmWgI4Mg2oyJqkN3pa8xNkZ3rSL37f9LrtQJRb3SXtjJLSaSxXSUIZyKBNQqAzqLugwZbNBlpw/Y9/U9Sczk5QjgouF2Rlp+oyhI1GN/8sdY+nNE18QYq70Uu95Why3PWijgrzo3W6oc/6RpJOyvJT6rqeMxp0S6j7R6ozkD4627aEoxcRLH4HEijsbFZEwU42gM6BV2vnA5vvduGWREoF5DfLdcVt/7yliERJg/TykKee4WLSjK4AplR65cj0l6eAKnaFfDTvD46uyJZkIfqCcl298tfVsDYcOcesX4Ox89sZhcpXtIejSrhkpOSwCe0gQoPCSEJKFJg+gHWnf0zIS2le38Mt9Ac5etSn9zvyKGUhzNdSMvoWDaWRdL0ONEPlay/dtIQCKMJK+XLO8pCjnjC4L4S+QTyN7tLFv2Q6gWW/9K5CCXd5GqQYaF9y5adW0Pt6ka6o/AovhUa1d36atRPN7WckRINkMz2ZSkgIaUWnkSMa124qQY3fr9QmVCDFcASp9UHscqg6hpUDspCWRGrpoLtInH+3eRwAlyl+XEBogybJt4cBAJ2+OSmB19tlVy/yH7WVYl4=
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$ANDROID_HOME"
