language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - build-tools-26.0.1
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - ".+"
script:
- "./gradlew clean assembleDebug"
notifications:
  email: false
  slack:
    secure: YbgzFLTx2AHh0PtOGEQykSaKVvo5Fh/X/dkQUkxn1BmVfdAfnEbJmIw9EJw2IpzbceXGWrFFM+ho3Or28MuD7GegNHEcC1QmWgI4Mg2oyJqkN3pa8xNkZ3rSL37f9LrtQJRb3SXtjJLSaSxXSUIZyKBNQqAzqLugwZbNBlpw/Y9/U9Sczk5QjgouF2Rlp+oyhI1GN/8sdY+nNE18QYq70Uu95Why3PWijgrzo3W6oc/6RpJOyvJT6rqeMxp0S6j7R6ozkD4627aEoxcRLH4HEijsbFZEwU42gM6BV2vnA5vvduGWREoF5DfLdcVt/7yliERJg/TykKee4WLSjK4AplR65cj0l6eAKnaFfDTvD46uyJZkIfqCcl298tfVsDYcOcesX4Ox89sZhcpXtIejSrhkpOSwCe0gQoPCSEJKFJg+gHWnf0zIS2le38Mt9Ac5etSn9zvyKGUhzNdSMvoWDaWRdL0ONEPlay/dtIQCKMJK+XLO8pCjnjC4L4S+QTyN7tLFv2Q6gWW/9K5CCXd5GqQYaF9y5adW0Pt6ka6o/AovhUa1d36atRPN7WckRINkMz2ZSkgIaUWnkSMa124qQY3fr9QmVCDFcASp9UHscqg6hpUDspCWRGrpoLtInH+3eRwAlyl+XEBogybJt4cBAJ2+OSmB19tlVy/yH7WVYl4=
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$ANDROID_HOME"
env:
  global:
  - secure: "g7JbUP2do/UCPsu/v+qTIMBIO75szrp7LyiTSVjUAz4DIk8xrNksiigCrpFb0FuS2uQ8ykWDfTDDKnAB0ex1apeNW4l6bb+YQdwvUd93DvX6xJcKtGUAFnoKFmVW9foUEXaemYJ06Ztph8OKfEQhHMlBzUPyGcfcUBBaODDU5Ow60JbWDgXvWRdUjhVqw0RmAJXqnYl5OQJvH2vyqqQ54Eh0z71Xxv+tQxFthIDPrWS7iNhp/ACZPKCtEnWn3Mt3V8yMIx6w+Lz6GLr/5ps2t5UCpQCSc3Mri3sFDI0GtG/g93PWi31YR1tAV+e7g/9vna9liktOkQxjBr8FIiy8uo4xLn+Fj2c6MD+x0jC3EHERYG2vMjXYpHvZHg9bpwJ+c6gOKUvRN/wk/yAxBlZPVAQmPaEAnIrCrKM8C4WSDlGb2BoiE9dZORBlLlO2HVRzJ07o1YIroEhxWbVHFPGQjXUsMEd+VDpFSsjFjSQqrXAmGG8ddc+7ZgLHQEXEWrseEh3Lyu441wllP8qFVGdKl3iT7wVz5OyHE6066DM+T7GuEpQjEuRoGP43I+gCAvQ5iK3IxBfxinD0wXOurtXfyXjOz4/n1pa3BMrJNc7AGkQmTz115DOgL8pQuxLRfTl4yI5O8LWp20b+0wSWuz27L+jGyn2CWa0SBsxtyRYouCY="
after_success:
- curl https://slack.com/api/files.upload -F token=${TOKEN} -F channels=#margarita -F title=Margarita-debug-$(date +"%Y%m%d-%H:%M").apk -F filename=app-debug.apk -F file=@app/build/outputs/apk/debug/app-debug.apk
